import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { Navigation } from '@/components/navigation';
import { Button } from '@/components/ui/button';
import { Search } from 'lucide-react';
import { Sidebar } from '@/components/sidebar';
import { Analytics } from '@vercel/analytics/next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-screen w-full flex-col bg-muted/40">
            {/* Top nav */}
            <header className="flex h-14 items-center border-b bg-background px-4 md:px-6">
              <Navigation />
              <Button variant="ghost" size="icon" className="ml-2 md:hidden">
                <Search className="h-4 w-4" />
                <span className="sr-only">Search</span>
              </Button>
              <div className="ml-2 hidden md:block">
                <label className="relative block">
                  <span className="absolute inset-y-0 left-0 flex items-center pl-3">
                    <Search className="h-4 w-4 text-muted-foreground" />
                  </span>
                  <input
                    type="text"
                    placeholder="Enter search term"
                    className="w-64 rounded-md border px-10 py-2 text-sm shadow hover:border-primary focus:outline-none"
                  />
                </label>
              </div>
            </header>
            <div className="flex flex-1 overflow-hidden">
              {/* Sidebar */}
              <aside className="hidden w-64 shrink-0 border-r bg-background px-6 py-6 lg:block">
                <Sidebar />
              </aside>

              {children}
              <Analytics />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
